spring.application.name=instruments
spring.profiles.active=dev

#dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA config generate tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
# URLs for OpenAPI servers
app.openapi.dev-url=http://localhost:8080
# Customize Swagger UI
springdoc.swagger-ui.tagsSorter=method
springdoc.swagger-ui.doc-expansion=list
